/// Gaia VGate register response
///
/// Source: biu/src/service/gaia-vgate-register.ts#GaiaVgateRegisterResponse
class GaiaVgateRegisterResponse {
  const GaiaVgateRegisterResponse({
    required this.code,
    required this.message,
    this.data,
  });

  factory GaiaVgateRegisterResponse.fromJson(Map<String, dynamic> json) {
    return GaiaVgateRegisterResponse(
      code: json['code'] as int? ?? -1,
      message: json['message'] as String? ?? '',
      data: json['data'] != null
          ? GaiaVgateRegisterData.fromJson(json['data'] as Map<String, dynamic>)
          : null,
    );
  }

  /// Return code: 0 success, 100000 captcha acquisition failed
  final int code;

  /// Error message
  final String message;

  /// Data payload
  final GaiaVgateRegisterData? data;

  bool get isSuccess => code == 0;
}

/// Gaia VGate register data
///
/// Source: biu/src/service/gaia-vgate-register.ts#GaiaVgateRegisterData
class GaiaVgateRegisterData {
  const GaiaVgateRegisterData({
    required this.type,
    required this.token,
    this.geetest,
  });

  factory GaiaVgateRegisterData.fromJson(Map<String, dynamic> json) {
    return GaiaVgateRegisterData(
      type: json['type'] as String? ?? '',
      token: json['token'] as String? ?? '',
      geetest: json['geetest'] != null
          ? GaiaGeetestInfo.fromJson(json['geetest'] as Map<String, dynamic>)
          : null,
    );
  }

  /// Verification type, currently only "geetest"
  final String type;

  /// Verification token (for subsequent validate)
  final String token;

  /// Geetest info; null means risk control cannot be lifted via captcha
  final GaiaGeetestInfo? geetest;
}

/// Geetest info for Gaia VGate
///
/// Source: biu/src/service/gaia-vgate-register.ts#GaiaGeetestInfo
class GaiaGeetestInfo {
  const GaiaGeetestInfo({
    required this.gt,
    required this.challenge,
  });

  factory GaiaGeetestInfo.fromJson(Map<String, dynamic> json) {
    return GaiaGeetestInfo(
      gt: json['gt'] as String? ?? '',
      challenge: json['challenge'] as String? ?? '',
    );
  }

  /// Geetest ID, usually a fixed value
  final String gt;

  /// Geetest KEY, generated by backend
  final String challenge;
}

/// Gaia VGate validate response
///
/// Source: biu/src/service/gaia-vgate-validate.ts#GaiaVgateValidateResponse
class GaiaVgateValidateResponse {
  const GaiaVgateValidateResponse({
    required this.code,
    required this.message,
    this.data,
  });

  factory GaiaVgateValidateResponse.fromJson(Map<String, dynamic> json) {
    return GaiaVgateValidateResponse(
      code: json['code'] as int? ?? -1,
      message: json['message'] as String? ?? '',
      data: json['data'] != null
          ? GaiaVgateValidateData.fromJson(json['data'] as Map<String, dynamic>)
          : null,
    );
  }

  /// Return code: 0 success, -111 csrf failed, 100003 captcha expired
  final int code;

  /// Error message
  final String message;

  /// Data payload
  final GaiaVgateValidateData? data;

  bool get isSuccess => code == 0;
}

/// Gaia VGate validate data
///
/// Source: biu/src/service/gaia-vgate-validate.ts#GaiaVgateValidateData
class GaiaVgateValidateData {
  const GaiaVgateValidateData({
    required this.isValid,
    required this.griskId,
  });

  factory GaiaVgateValidateData.fromJson(Map<String, dynamic> json) {
    return GaiaVgateValidateData(
      isValid: json['is_valid'] as int? ?? 0,
      griskId: json['grisk_id'] as String? ?? '',
    );
  }

  /// Validation result: 1 means success
  final int isValid;

  /// gaia_vtoken (for resuming normal access)
  final String griskId;

  bool get isSuccessful => isValid == 1;
}
